"""peft utils interface."""

from .config import PeftConfig, PetuningConfig

from .mapping import TRANSFORMERS_MODELS_ROME_LAYER_MODULES_MAPPING
from .mapping import TRANSFORMERS_MODELS_TO_ADALORA_TARGET_MODULES_MAPPING
from .mapping import TRANSFORMERS_MODELS_TO_LORA_TARGET_MODULES_MAPPING
from .mapping import TRANSFORMERS_MODELS_TO_LORA_LAGE_TARGET_MODULES_MAPPING
from .mapping import TRANSFORMERS_MODELS_TO_PREFIX_TUNING_POSTPROCESS_MAPPING
from .mapping import TRANSFORMERS_MODELS_TO_ROUTELORA_TARGET_MODULES_MAPPING
from .mapping import WEIGHTS_NAME, CONFIG_NAME
from .mapping import bloom_model_postprocess_past_key_value

from .others import get_peft_model_state_dict, set_peft_model_state_dict, _freeze_model, prepare_model_for_kbit_training